import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { environment } from 'environments/environment';
import { Observable, of, throwError } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class FormService {

  furniture = [
    { nama: 'Perlengkapan Umum', jenis: 'divider' },
    { nama: "Kursi Teras" },
    { nama: "Sofa/Kursi Tamu" },
    { nama: "Meja TV" },
    { nama: "Meja Kerja + Kursi" },
    { nama: "Lemari Rak Buku" },
    { nama: "Lemari Buffet (Dresoir)" },
    { nama: "Meja + Kursi Makan" },
    { nama: "Lemari Makan" },
    { nama: "Spring Bed 200 x 160" },
    { nama: "Spr ng Bed 200 x I60" },
    { nama: "Spring Bed 200 x 90" },
    { nama: "Tempat Tidur Engkle 200 x 90 + Kasur" },
    { nama: "Baby Comode/Baby Bed" },
    { nama: "Kursi Kamar" },
    { nama: "Mea Rias (Tualet)" },
    { nama: "Meja Dapur + Kursi" },
    { nama: "Rak Piring" },
    { nama: "Mela Setrika" },
    { nama: "Rak Handuk" },
    { nama: "Rak Sepatu" },
    { nama: "Rak Jemuran" },
    { nama: "Lemari Pakaian 3/2 Pintu" },
    { nama: "teman Pakaian 1 Pintu" },
    { nama: "Tempat Tidur Pembantu + Kasur" },
    { nama: "Kompor Gas 4 Pit" },
    { nama: "Kompor Gas 2 Pit" },
    { nama: "Tabung LPG" },
    { nama: "Lemari Es 2 Pintu Besar" },
    { nama: "Lemari Es 2 Pintu Sedang" },
    { nama: "Lemari Es 1 Pintu Sedang" },
    { nama: "Microwave" },
    { nama: "Juicer" },
    { nama: "Blender" },
    { nama: "Rice Box" },
    { nama: "Exhaust Fan" },
    { nama: "Alat Pendingin Ruangan (AC)" },
    { nama: "Water Heater" },
    { nama: "Vacum Cleaner" },
    { nama: "Televisi" },
    { nama: "Mesin Cuci" },
    { nama: "Dispenser" },
    { nama: "Meja Belajar" },
    { nama: "Karpet Nobel" },
    { nama: "Lampu Emergency" },
    { nama: 'Perlengkapan Linen', jenis: 'divider' },
    { nama: "Gordyn Vitrage" },
    { nama: "Sprei Double +  Bed Cover" },
    { nama: "Sprei Single + Bed Cover" },
    { nama: "Selimut Wool" },
    { nama: "Taplak Meta Makan" },
    { nama: "Tapïak Meja Tamu" },
    { nama: "Lap Makan (Damast)" },
    { nama: "Lap Piring" },
    { nama: "Kesed/Karpet" },
    { nama: 'Perlengkapan Makan', jenis: 'divider' },
    { nama: "Pirinp Makan Cekung" },
    { nama: "Piring Makan Ceper" },
    { nama: "Sendok Maman" },
    { nama: "Garpu Makan" },
    { nama: "Pisau Makan" },
    { nama: "Kobokan/Cucian tangan" },
    { nama: "Gelas Minum HS" },
    { nama: "Cangkir Kopj & Tatakan" },
    { nama: "Sendok teh" },
    { nama: "Tempat Gula,Teh, Kops" },
    { nama: "Piring Buah" },
    { nama: "Mangkuk Sop" },
    { nama: "Baki/Nampan Kayu" },
    { nama: "Ceret/Teko Kopi 8 tefi" },
    { nama: "Thermos" },
    { nama: "Tempat Mentega" },
    { nama: "Tempat Garam & Lada" },
    { nama: "Asbak" },
    { nama: "Tempat Saus" },
    { nama: "Tempat Kue Kristal" },
    { nama: "Tempat Buah Bowl Set" },
    { nama: "Baki Stainless Steel" },
    { nama: "Tempat Nasi Keramik" },
    { nama: "Kitchen Set" },
    { nama: "Mixer" },
    { nama: "Rice Cooker" },
    { nama: "Pemanggang Rofi" },
    { nama: "Silver Wove" },
    { nama: "Tempat Sampah Plaslik" },
    { nama: "Lodor Besar" },
    { nama: "Tempat Puding" },
    { nama: "Mankok Bakso" },
    { nama: "Terpat Roti" },
    { nama: "Sendok Sup/Sayur" },
    { nama: 'Perlengkapan Dapur', jenis: 'divider' },
    { nama: "WaJan" },
    { nama: "Tempat Nasi" },
    { nama: "Sodet" },
    { nama: "Panci Masak" },
    { nama: "Pisau Dapur" },
    { nama: "Tempat Sayur" },
    { nama: "Langseng" },
  ]

  atk = [
    { nama: 'Self Adhesive Label no. 121, 38 X 75 mm, ' },
    { nama: 'Ballpoint Faster C6 High Grade fine Biru, 12 pens per box.' },
    { nama: 'Ballpoint Faster C6 High Grade fine Hitam, 12 pens per box.' },
    { nama: 'Ballpoint Gel Ink Biru Pilot G2, 12 pens per box.' },
    { nama: 'Bantex Post Binder 13910 A4 Kim Jim 8cm Blue' },
    { nama: 'Bantex Post Binder A6 6CM' },
    { nama: 'BINDER (ORDNER), 7 CM, BLUE TYPE : 1465-01 COLOUR : BLUE THICKNESS : 7 CM PAPER SIZE : A5 MANUFACTURE : BANTEX ' },
    { nama: 'BINDER (ORDNER), 7.5 CM, BLUE TYPE : 1465-01 COLOUR : BLUE THICKNESS : 7.5 CM PAPER SIZE : A4 MANUFACTURE : BANTEX ' },
    { nama: 'Binder Clip No.105, width 1/2" / 15 mm, 12 pcs per box.' },
    { nama: 'Binder Clip No.107, width 3/4" / 19 mm, 12 pcs per box.' },
    { nama: 'Binder Clip No.111, width 1" / 25 mm, 12 pcs per box.' },
    { nama: 'Binder Clip No.155, width 1.1/4" / 32 mm, 12 pcs per box.' },
    { nama: 'Binder Clip No.200, width 1.5/8" / 41 mm, 12 pcs per box.' },
    { nama: 'Binder Clip No.260, width 2" / 51 mm, 12 pcs per box.' },
    { nama: 'BINDER RING INSERT 8542 A4 WHITE BANTEX 2D 65 MM' },
    { nama: 'BINDER RING INSERT WHITE FOLIO BANTEX 65 MM' },
    { nama: 'Block Note Garis No.15' },
    { nama: 'Book Cover Plastik A4' },
    { nama: 'BOOK ENDS, IRON' },
    { nama: 'Book, Ekspedisi' },
    { nama: 'Box plastic jumbo type 1034, blue color, 110 X 260 X 320 mm' },
    { nama: 'Buku Agenda Surat Masuk logo PT. Pertamina EP isi 100 Lembar per buku' },
    { nama: 'CORRECTION FLUID ( TIP EX 20 ML NO.4203 ) CONTENT OF 1 BOTTLE OF CORRECTION FLUID 20 ML AND 1 BOTTLE THINNER 20 ML' },
    { nama: 'CORRECTION PEN EX PENTEL - ZL31' },
    { nama: 'CORRECTION TAPE (TIP-EX KERTAS) JOYCO' },
    { nama: 'Cover Jilid Kertas A4 / Buffalo Tebal (isi 10 per pack)' },
    { nama: 'Cutter Besar L500 ' },
    { nama: 'CUTTER BLADE BIG L150 CONTENTS OF : 5 PCS PER TUBE' },
    { nama: 'CUTTER BLADE SMALL A100' },
    { nama: 'Cutter Kecil A300 ' },
    { nama: 'Divider Size A4 Multiholes' },
    { nama: 'DUCT TAPE BLACK / CLOTH TAPE FOR BIND WIDE : 48 MM' },
    { nama: 'DUCT TAPE BROWN WIDE : 48 MM' },
    { nama: 'DUCT TAPE TRANSPARENT WIDE : 48 MM' },
    { nama: 'DURACLIPS NO 2200 A4 BLUE 06' },
    { nama: 'DURACLIPS NO 2201 F4 BLUE 06 2201' },
    { nama: 'ENVELOPE BROWN A3 LOGO PERTAMINA EP' },
    { nama: 'ENVELOPE BROWN A4 LOGO PERTAMINA EP' },
    { nama: 'ENVELOPE BROWN A5 LOGO PERTAMINA EP' },
    { nama: 'ENVELOPE BROWN F4 LOGO PERTAMINA EP' },
    { nama: 'ERASER , WHITEBOARD' },
    { nama: 'ERASER TYPE : PENCIL' },
    { nama: 'FOLDER PAPER DIAMOND NO 5002 FOLIO' },
    { nama: 'GLUE PAPER POLISH SMALL SIZE' },
    { nama: 'INK, STAMP' },
    { nama: 'MAGNET WALL MN 30-S DIA 30 MM' },
    { nama: 'Map clear holder 40 A4' },
    { nama: 'Map Clear slevees Plastik Bening for A4 paper size, Single Pocket, 12 pcs per pack' },
    { nama: 'Map Clear slevees Plastik Bening for F4 paper size, Single Pocket, 12 pcs per pack' },
    { nama: 'Map plastik for paper size A4, perforated sheet (2 holes), 6 pcs per pack ' },
    { nama: 'MATERAI ' },
    { nama: 'NOTE TYPE : MARK' },
    { nama: 'Note, Post It, Colour, Mark Please Sign' },
    { nama: 'PAPER CONCORDE A4 160 GR (PACK OF 10 SHEETS)' },
    { nama: 'PAPER PUNCHER TYPE : NO. 30' },
    { nama: 'PAPER PUNCHER TYPE : NO. 85B' },
    { nama: 'PAPER TYPE : HVS COLOUR : WHITE SIZE : A4 WEIGHT : 80 GRAM' },
    { nama: 'PAPER, CARTOON' },
    { nama: 'PAPER, HVS, A4, 70GR' },
    { nama: 'PAPER, HVS, F4, 70GR' },
    { nama: 'PENCIL MARS LUMOGRAPH 100-2B STEADLER, 1 DOZ OF 12 EA' },
    { nama: 'PENCIL SHARPENER ANGEL-5' },
    { nama: 'PERMANENT GLUE STICK FOR PAPER AND FABRIC, 8 GRAM' },
    { nama: 'POCKET BAMBI F4 PP 5111 @10/PACK' },
    { nama: 'POST-IT NOTE 3M NO. 653 YELLOW' },
    { nama: 'POST-IT NOTE 3M NO. 654 YELLOW' },
    { nama: 'POST-IT NOTE 3M NO. 655 YELLOW' },
    { nama: 'POST-IT NOTE 3M NO. 656 YELLOW' },
    { nama: 'PUSH PIN NAILS TO STICKER PAPER. THE CONTENTS OF : 30' },
    { nama: 'RING BINDER TYPE : INSERT SIZE : 25 MM A4 WHITE, 2D BANTEX' },
    { nama: 'RING BINDER TYPE : INSERT SIZE : 40 MM A4 WHITE, 2D BANTEX' },
    { nama: 'RING SPIRAL WIRE 10 MM, 3/8" (65 LBR)' },
    { nama: 'RING SPIRAL WIRE 14 MM, 9/16" (125 LBR)' },
    { nama: 'RING SPIRAL WIRE 19 MM, 3/4" (165 LBR)' },
    { nama: 'RULER MATERIAL : IRON SIZE : 30 CM' },
    { nama: 'SCISSOR, BIG' },
    { nama: 'SCISSOR, MEDIUM' },
    { nama: 'SPIDOL WHITEBOARD MARKER BLACK' },
    { nama: 'SPIDOL WHITEBOARD MARKER BLUE' },
    { nama: 'SPIDOL WHITEBOARD MARKER RED' },
    { nama: 'SPIDOL, ARTLINE 70, RED, PERMANENT' },
    { nama: 'SPIDOL, TYPE : ARTLINE 70, COLOUR : BLACK, ADDITIONAL DETAIL : PERMANENT' },
    { nama: 'SPIDOL, TYPE : ARTLINE 70, COLOUR : BLUE, ADDITIONAL DETAIL : PERMANENT' },
    { nama: 'STABILLO BOSS BLUE' },
    { nama: 'STABILLO BOSS GREEN' },
    { nama: 'STABILLO BOSS ORANGE' },
    { nama: 'STABILLO BOSS PINK' },
    { nama: 'STABILLO BOSS UNGU' },
    { nama: 'STABILLO BOSS YELLOW' },
    { nama: 'STAPLER TYPE : MAX HD-10' },
    { nama: 'STAPLER TYPE : MAX HD-50' },
    { nama: 'STAPLES, NO. 10-1M' },
    { nama: 'STAPLES, NO. 3-1M' },
    { nama: 'TAPE TYPE : DISPENSER NO. 07' },
    { nama: 'TAPE TYPE : DISPENSER NO. 50' },
    { nama: 'TAPE TYPE : SELF ADHESIVE SIZE 1 IN X 72 YARD CELLULOSE' },
    { nama: 'TAPE TYPE SELF ADHESIVE SIZE : 1.2 IN X 72 YARD YDS PANFIX' },
    { nama: 'TAPE, CELLOPHANE, DOUBLE, KENKO' },
    { nama: 'TRIGONAL PAPER CLIPS SEA GULL NO. 3' },
    { nama: 'TYPE WRITER, RIBBON CORRECTABLE FILM TYPE :1030 MANUFACTURE : BROTHER' },
    { nama: 'White Envelope Plain Jaya No. 90' },

  ]

  variasi = {
    rdp: 'perbaikan',
    furniture: 'furniture',
    rumput: 'pemotongan',
    ac: 'perbaikan',
    atk: 'atk',
    acara: 'kebutuhan',
    peralatan: 'peralatan'
  }

  constructor() { }
}
